services:
  - type: web
    name: MediOnDocs-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
    plan: free
